name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security_and_quality:
    name: Security and Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Install Pylint
        run: |
          pip install pylint

      - name: Run Pylint
        run: |
          pylint --fail-under=8 app

      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: '-q'
          click-to-expand: true
          report-title: 'Test Report'

      - name: Install Pytest Dependencies
        run: pip install pytest pytest-md pytest-emoji
      - name: Run SAST
        uses: mdegis/bandit-action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: "tests/test_jwt.py"
          level: high
          confidence: high
          exit_zero: true
