name: Tests and Security Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security:
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Install dependencies
        run: |
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r . -ll